# Generated by Django 5.2.10 on 2026-01-20 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255, verbose_name='세션 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, help_text='세션 소유자 (비로그인 시 null 가능)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI 상담사'), ('system', '시스템')], max_length=20)),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('sources', models.JSONField(blank=True, default=list, help_text='검색된 MFDS 정보 등 JSON 저장', verbose_name='참조 출처 (제품/문서)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chatbot.chatsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
