# Generated by Django 5.2.10 on 2026-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='검색된 상품 정보 등 JSON 저장', verbose_name='참조 출처 (제품/문서)'),
        ),
    ]
