# Generated by Django 5.2.10 on 2026-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='사용자 ID')),
                ('supplement_id', models.IntegerField(db_index=True, verbose_name='영양제 ID')),
                ('notify_price_drop', models.BooleanField(default=False, verbose_name='가격 하락 알림')),
                ('target_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='목표 가격')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜 목록',
                'ordering': ['-added_at'],
                'unique_together': {('user_id', 'supplement_id')},
            },
        ),
    ]
