# Generated by Django 5.2.10 on 2026-01-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('product_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'db_table': 'wishlist_items',
                'unique_together': {('user_id', 'product_id', 'platform')},
            },
        ),
    ]
