# Generated by Django 5.2.10 on 2026-01-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('original_price', models.IntegerField(verbose_name='Original Price')),
                ('current_price', models.IntegerField(verbose_name='Current Price')),
                ('price_drop_percent', models.FloatField(verbose_name='Price Drop Percent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='wishlist.wishlistitem')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'db_table': 'price_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
