# Generated by Django 5.2.10 on 2026-01-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_pricehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricehistory',
            new_name='price_histo_wishlis_97891f_idx',
            old_name='price_histo_wishlis_idx',
        ),
    ]
