# Generated by Django 5.2.10 on 2026-01-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_coupangmanualproduct'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupangmanualproduct',
            new_name='search_coup_is_acti_203bcf_idx',
            old_name='search_coup_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='coupangmanualproduct',
            new_name='search_coup_categor_ef44cc_idx',
            old_name='search_coup_categor_idx',
        ),
    ]
