# Generated by Django 5.2.10 on 2026-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_search_coup_is_acti_idx_search_coup_is_acti_203bcf_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, help_text='naver, 11st', max_length=20, verbose_name='플랫폼')),
                ('product_id', models.CharField(db_index=True, max_length=200, verbose_name='상품 ID')),
                ('product_name', models.CharField(max_length=500, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('original_price', models.IntegerField(blank=True, null=True, verbose_name='원가')),
                ('discount_percent', models.IntegerField(blank=True, null=True, verbose_name='할인율')),
                ('image_url', models.URLField(max_length=1000, verbose_name='이미지 URL')),
                ('product_url', models.URLField(max_length=1000, verbose_name='상품 URL')),
                ('mall_name', models.CharField(blank=True, max_length=100, verbose_name='판매처')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='평점')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰 수')),
                ('search_keyword', models.CharField(db_index=True, help_text='이 상품을 찾은 검색어', max_length=200, verbose_name='검색 키워드')),
                ('cached_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='캐시 시간')),
            ],
            options={
                'verbose_name': '상품 캐시',
                'verbose_name_plural': '상품 캐시 목록',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['search_keyword', '-cached_at'], name='search_prod_search__4ddb02_idx'), models.Index(fields=['platform', '-cached_at'], name='search_prod_platfor_fef7a2_idx')],
                'unique_together': {('platform', 'product_id')},
            },
        ),
    ]
