# Generated by Django 5.2.10 on 2026-01-20 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('user_id', models.IntegerField(db_index=True, verbose_name='사용자 ID')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('paid', '결제 완료'), ('shipping', '배송중'), ('delivered', '배송 완료'), ('cancelled', '취소됨'), ('refunded', '환불됨')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='총 금액')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='받는 분')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('shipping_address', models.TextField(verbose_name='배송 주소')),
                ('shipping_memo', models.CharField(blank=True, max_length=200, verbose_name='배송 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_id', models.IntegerField(verbose_name='영양제 ID')),
                ('platform', models.CharField(max_length=50, verbose_name='구매 플랫폼')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='단가')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.order')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('method', models.CharField(choices=[('card', '카드'), ('transfer', '계좌이체'), ('virtual', '가상계좌'), ('phone', '휴대폰'), ('toss', '토스페이'), ('kakao', '카카오페이'), ('naver', '네이버페이')], max_length=20)),
                ('status', models.CharField(choices=[('ready', '준비'), ('in_progress', '진행중'), ('done', '완료'), ('cancelled', '취소'), ('failed', '실패')], default='ready', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='결제 금액')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시각')),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payments.order')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제 목록',
            },
        ),
    ]
