# Generated by Django 5.2.10 on 2026-01-19 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('serving_size', models.CharField(max_length=50, verbose_name='1회 섭취량')),
                ('servings_per_container', models.PositiveIntegerField(default=1, verbose_name='총 섭취횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '영양제',
                'verbose_name_plural': '영양제 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MFDSHealthFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='인허가번호')),
                ('report_number', models.CharField(db_index=True, max_length=100, verbose_name='품목제조번호')),
                ('product_name', models.CharField(db_index=True, max_length=500, verbose_name='품목명')),
                ('company_name', models.CharField(db_index=True, max_length=200, verbose_name='업소명')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='보고일자')),
                ('expiry_period', models.CharField(blank=True, max_length=100, verbose_name='소비기한')),
                ('appearance', models.TextField(blank=True, verbose_name='성상')),
                ('intake_method', models.TextField(blank=True, verbose_name='섭취방법')),
                ('functionality', models.TextField(blank=True, verbose_name='주된기능성')),
                ('cautions', models.TextField(blank=True, verbose_name='섭취시주의사항')),
                ('storage_method', models.TextField(blank=True, verbose_name='보관방법')),
                ('shape', models.CharField(blank=True, max_length=100, verbose_name='형태')),
                ('standard', models.TextField(blank=True, verbose_name='기준규격')),
                ('raw_materials', models.TextField(blank=True, verbose_name='원재료')),
                ('product_form', models.CharField(blank=True, max_length=100, verbose_name='제품형태')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '식약처 건강기능식품',
                'verbose_name_plural': '식약처 건강기능식품 목록',
                'ordering': ['-synced_at'],
                'indexes': [models.Index(fields=['product_name'], name='supplements_product_abe1a3_idx'), models.Index(fields=['company_name'], name='supplements_company_e97f16_idx'), models.Index(fields=['functionality'], name='supplements_functio_c6106a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='성분명')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='함량')),
                ('unit', models.CharField(choices=[('mg', '밀리그램'), ('mcg', '마이크로그램'), ('g', '그램'), ('IU', '국제단위'), ('CFU', 'CFU'), ('ml', '밀리리터')], max_length=20, verbose_name='단위')),
                ('daily_value_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='일일 권장량 %')),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='supplements.supplement', verbose_name='영양제')),
            ],
            options={
                'verbose_name': '성분',
                'verbose_name_plural': '성분 목록',
                'ordering': ['name'],
            },
        ),
    ]
