# Generated by Django 5.2.10 on 2026-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0001_add_mfds_healthfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='benefits',
            field=models.JSONField(blank=True, default=list, verbose_name='주요 효능'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='description',
            field=models.TextField(blank=True, verbose_name='AI 제품 설명'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='target_audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='추천 대상'),
        ),
    ]
