# Generated by Django 5.2.10 on 2026-01-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='사용자 ID')),
                ('supplement_id', models.IntegerField(db_index=True, verbose_name='영양제 ID')),
                ('target_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='목표 가격(원)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='알림 발송 시각')),
            ],
            options={
                'verbose_name': '가격 알림',
                'verbose_name_plural': '가격 알림 목록',
                'unique_together': {('user_id', 'supplement_id')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_id', models.IntegerField(db_index=True, verbose_name='영양제 ID')),
                ('platform', models.CharField(choices=[('iherb', 'iHerb'), ('coupang', '쿠팡'), ('naver', '네이버'), ('amazon', 'Amazon'), ('costco', '코스트코'), ('other', '기타')], max_length=50, verbose_name='판매 플랫폼')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='가격(원)')),
                ('original_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='정가')),
                ('url', models.URLField(blank=True, verbose_name='상품 URL')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='재고 여부')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '가격 기록',
                'verbose_name_plural': '가격 기록 목록',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['supplement_id', 'platform', '-recorded_at'], name='prices_pric_supplem_f830f3_idx')],
            },
        ),
    ]
